### ISSUE TITLE
Spatne linky na chybove strance

### ISSUE THREAD

**Issue by radekhubner** [HlidacStatu/HlidacStatu#12]
Na chybove strance https://www.hlidacstatu.cz/Error404 (ale take na error 500) se v menu v pravo nahore zobrazuji linky NASTAVENÍ ÚČTU a ODHLÁSIT i kdyz jsem odhlaseny.

https://github.com/HlidacStatu/HlidacStatu/blob/0f8d3c55a142803f24297b17942613b7f23065f0/Web.Statu/404.html#L138

https://github.com/HlidacStatu/HlidacStatu/blob/0f8d3c55a142803f24297b17942613b7f23065f0/Web.Statu/404.html#L141

Neni tam podminka, jelikoz je to jen ciste html. https://github.com/HlidacStatu/HlidacStatu/blob/0f8d3c55a142803f24297b17942613b7f23065f0/Web.Statu/Views/Shared/_Layout.cshtml#L258

Stranky take maji jeste stary layout. Mam udelat PR na pouziti noveho layoutu? Co s chybou, kterou popisuju, odstranime menu pro ucet uplne?

**Comment by rpliva** [comment]
Pokud predelas chybove stranky do noveho layoutu a posles PR, bude to skvele. Menu pro prihlasene uzivatele bych na techto strankach vubec nedobrazoval.

**Comment by michalblaha** [comment]
Diky!
