### ISSUE TITLE
HlidacSmluv.cz vrací 404

### ISSUE THREAD

**Issue by mhujer** [HlidacStatu/HlidacStatu#20]
Všiml jsem si, že HlidacSmluv.cz vrací 404ku a smlouvy jsou nově na https://www.hlidacstatu.cz/smlouvy

Bylo by fajn původní web přesměrovat, určitě na něj (a na jednotlivé stránky tam) vedou odkazy a web má podle `site:hlidacsmluv.cz` na Google zaindexovaných ~79k stránek.

**Comment by katkubi** [comment]
ahoj, umis s tim pomoct?

**Comment by mhujer** [comment]
@katkubi Ahoj, no vzhledem k tomu, že nikde nemám přístupy a ani netuším, kde a jak to běží, tak si nejsem jistý. Issue jsem založil místo toho, abych to psal jen @michalblaha do mailu.

Z toho, co jsem koukal, to vypadá, že by mělo stačit na tom původním webu udělat přesměrování všeho 1:1 (struktura URL se neměnila, jen jsou na nové doméně)

**Comment by michalblaha** [comment]
Diky moc za upozornění. Upraveno nastaveni Webserveru a je to jiz ok.
