### ISSUE TITLE
Data - možnost řazení

### ISSUE THREAD

**Issue by michalskop** [HlidacStatu/HlidacStatu#21]
Ocenil bych možnost řazení výstupů v Datech.

Např. tabulku v https://www.hlidacstatu.cz/data/Hledat/faktury-mesto-plasy-2018?Q=*HKM seřadit dle data úhrady nebo dle evidenčního čísla.

**Comment by michalblaha** [comment]
to samozrejme jde. pri registraci datasetu je to pole "orderList" 

viz https://hlidacstatu.docs.apiary.io/#reference/datasety-rozsirene-datove-sady-hlidace-statu/datasety/registrace-nove-datove-sady

"orderList": [["Nabytí právní moci", "PravniMoc"], ["Účastníci", "Ucastnici.Jmeno.keyword"]]
