### ISSUE TITLE
Data - provázání dle IČO

### ISSUE THREAD

**Issue by michalskop** [HlidacStatu/HlidacStatu#22]
Bylo by fajt, kdyby v datech se automaticky zlinkovaly údaje v případě, že v datech jsou IČOa.

Příklad: https://www.hlidacstatu.cz/data/Hledat/faktury-mesto-plasy-2018?q=*&order=DbCreated+desc - aby jednotlivé řádky byly rovnou prolinkované na příslušnou stránku hlídače, např. https://www.hlidacstatu.cz/subjekt/74462563

**Comment by michalblaha** [comment]
Ale to samozrejme jde. Viz https://hlidacstatu.docs.apiary.io/#reference/datasety-rozsirene-datove-sady-hlidace-statu/datasety

ale dataset nesmi byt v "bete"
