### ISSUE TITLE
Administrace pro NasiPolitici/Hlidac eventy 

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/HlidacStatu#24]
Událost
Navrhuji zadefinovat tzn. `událost`, což je strukturovaná informace, která je vždy spojena s osobou.

```
Obsahuje tyto údaje:
- ID osoby
- typ události (viz Seznam I)
- subType události (viz poznamky u Seznam I)
- kdy událost nastala (volitelně)
- kdy událost skončila (volitelně)
- vazba na politickou stranu (volitelně)
- Titulek udalosti (povinně)
- Popis události (volitelně)
- číselná hodnota (volitelne, použito typicky u daru politickým stranám)
- textová hodnota (volitelné, typicky nějaká JSON struktura pro speciální využití)
```

Dnes jsou temer totožné SQL tabulky `OsobaEvent` a `FirmaEvent`

================
Je potreba web rozhraní, které umožní autoriz.uživatelům
- nalézt a vypsat Events
- měnit  Events
- přidávat a mazat
- srozumitelný editor pro BFU
- schvalování/odmítání oprav a nových events (dnes přes SQL tabulku Review)

Ostatní veřejnost má možnost navrhnou opravu/novy Event, kterou autoriz.uzivatel schvali 

Pro verejnost:
- navrzení nového eventu
- navrzení opravy eventu
- odeslani emailu s navrhem autoriz.uzivatelum
- odeslani prijeti/neprijeti navrhu od autoriz.uzivatele. U neprijeti s oduvodnenim.

**Comment by suchoss** [comment]
Shrnutí zadání:

1. Vytvořit ASP.NET Core 2.2 MVC projekt
    - v projektu vytvořit controller pro editaci `OsobaEvent` a `FirmaEvent` (oba dva již existují v SQL db k Hlídači státu)
    - ke controlleru nějaké základní view (Razor pages)
    - dohromady by to mělo umět to co jsi psal výše:  

      Autorizovaní uživatelé:
      > nalézt a vypsat Events
      > měnit Events
      > přidávat a mazat
      > schvalování/odmítání oprav a nových events (dnes přes SQL tabulku Review)

      Veřejnost:
      > navrzení nového eventu
      > navrzení opravy eventu
      > odeslani emailu s navrhem autoriz.uzivatelum
      > odeslani prijeti/neprijeti navrhu od autoriz.uzivatele. U neprijeti s oduvodnenim.
2. Projdu si, jak je to dělané dnes (`OsobaEvent` a `FirmaEvent`, SQL tabulku Review). Rozšířím současné tabulky s událostma o nové sloupce.

**Comment by suchoss** [comment]
Udělali jsme trochu jinak po nahrání nových eventů se struktura změnila viz kód https://github.com/HlidacStatu/HlidacStatu/commit/8bf79a4f23b69b076b4db7ef2ce0f503b1524170
