### ISSUE TITLE
Dotace - vyhledávání podle jména a IČO

### ISSUE THREAD

**Issue by Eliska12** [HlidacStatu/HlidacStatu#48]
Nefunguje dobře vyhledávání v dotacích. 
![chyba 1](https://user-images.githubusercontent.com/57462675/77247378-e6861b80-6c30-11ea-8bf3-1db8c45225f4.png)
![chyba 2](https://user-images.githubusercontent.com/57462675/77247379-e7b74880-6c30-11ea-83c3-1a018caaa641.png)

Příklad - Mendelova univerzita v Brně 
IČO: 62156489

Při vyhledání podle jména se nezobrazí ve sloupečku prolinkované IČO.
Při vyhledání podle IČO univerzity se zobrazí vše.

https://www.hlidacstatu.cz/dotace/hledat?Q=jmeno%3A%22Mendelova+univerzita+v+Brn%C4%9B%22

**Comment by suchoss** [comment]
opraveno
