### ISSUE TITLE
doplnění dotací z dotacni-parazit.cz

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/HlidacStatu#6]

**Comment by kokes** [comment]
Nechceš jít přímo ke zdroji? Který konkrétní dotační databáze tě zajímaj?

**Comment by michalblaha** [comment]
@kokes z rozhovoru s klukama od Dotacniho parazita jsem pochpil, ze mira cisteni, integrace, deduplikace atd. je netrivialni. 
Data v ruznych rejstricich se duplikuji, obcas nesedi atd.

Ja se priznam, ze na to nemam zejmena znalosti a energii.

**Comment by suchoss** [comment]
Aktuální stav ke dnešnímu dni:
- Data máme z dotačního parazita, ale možná opravdu půjdeme rovnou ke zdroji.
- Zatím máme zpracovaná data pouze z CEDRu (zdroj je v tuto chvíli Dotační parazit). Snad během tohoto týdne stihneme spustit v produkci.
- Budeme potřebovat ještě zpracovat data z těchto zdrojů: DotInfo, SZIF, CzechInvest, Strukturální fondy. Jako zdroj se zatím může použít [Dotační parazit](https://dotacni-parazit.cz/opendata)
- Na DotInfo snad už někoho máme.

Dotazy piště klidně sem.

**Comment by kokes** [comment]
- DotInfo - existuje jen 2 roky starý export, který má navíc chyby v exportu (hlášeno někdy loni @SmallHillCz, ale zatim bez nápravy)
- SZIF - existují dva roky open dat, ale BEZ identifikátorů firem (IČO), takže je to celkem nepříjemný na práci (a párování podle názvu neni moc košér)
- CzechInvest - u starších dat je třeba doplnit IČO, pač tam chybí - viz např. https://github.com/kokes/od/blob/master/data/czechinvest/data/slovnik.csv - je to ale jednorázová práce
- Strukturální fondy - na 2014-2020 existují open data (XML), na 2007-2013 jsou jen Excely, ale celkem zpracovatelné (a v tuhle chvíli už statické), takže tohle jsou celkem cajk zdroje

**Comment by suchoss** [comment]
@kokes 
Díky za info ke zdrojům. K tomu DotInfo - už řeší @michalblaha snad si to ministerstvo opraví. Případně je tu ještě alternativa to vytahat z jejich webu.

**Comment by suchoss** [comment]
Tak na datech ke strukturálním fondům snad bude pracovat @jakubskopal

Data by měla být dostupná zde:

**za období od 2014:**
 - [2014 - 2020](https://www.dotaceeu.cz/cs/Informace-o-cerpani/Seznamy-prijemcu)  - stačí stáhnout (Seznam operací (List of operations) 1/11/2019 ) - aktualizují ho každý měsíc

**k tomu je potřeba ještě stáhnout seznam za období do 2014**
 - [dotace - 2013](https://www.dotaceeu.cz/Dotace/media/SF/Informace%20o%20%c4%8derp%c3%a1n%c3%ad/Seznamy%20p%c5%99%c3%adjemc%c5%af%20(List%20of%20Beneficiaries)/P%c5%99ehled%20projekt%c5%af/Prehled_projektu_20160603upraveno.xlsx)

    - pokud by nefungoval ten odkaz za 2013, tak tady je návod, jak se k tomu dostat):
> https://www.dotaceeu.cz/cs/Evropske-fondy-v-CR/Programove-obdobi-2007-2013/Cerpani-v-obdobi-2007-2013
> Jedná se o období 2007 - 2013, souhrn najdete ve složce Seznam příjemců - Přehled projektů za PO 2007-2013 - ten soubor z června 2016. Tento je skutečně souhrnný, takže tam najdete i staré PRV a OP R 

**a za období do 2006:**
 - [poslední odkaz dole s nápisem "Přehled projektů za období 2004-2006 řazený podle regionů je ke stažení"](https://www.dotaceeu.cz/cs/Evropske-fondy-v-CR/Programove-obdobi-2004-2006-(1)/Vysledky-cerpani)

**Comment by suchoss** [comment]
K SZIF jsem zatím dostal [tenhle odkaz](https://www.szif.cz/cs/seznam-prijemcu-dotaci), ale ještě jsem na to blíže nekoukal.

**Comment by suchoss** [comment]
@kokes aha, díky. Jsem slepej a tu informaci jsem přehlédl.

**Comment by suchoss** [comment]
Aktuální stav:
Máme zpracované dotace CEDR, DotInfo a SZIF (díky @gyfis).

**Comment by suchoss** [comment]
Update. Už je skoro hotový i CzechInvest.

**Comment by suchoss** [comment]
Aktuálně máme všechny zdroje. Jen je potřeba ještě doladit strukturu u szif a czechinvestu. Také řešíme chyby v CEDRu.
