### ISSUE TITLE
"Nulové" IČO (K-index)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/HlidacStatu#60]
Pozor - U města Karviná se s fyzickými osobami (IČO 00000000) spárovala chybně uvedená soukromá firma (sponzor) a to může mít v některých parametrech vliv na hodnocení.

Tady smlouva s fyz.osobami a níže navázáno chybně na toho sponzora:
https://www.hlidacstatu.cz/Detail/11146520
https://www.hlidacstatu.cz/Detail/8599903

Tady ten subjekt: https://www.hlidacstatu.cz/Subjekt/00000000 (C/ECON spol. s r.o., správné IČO 48113328)

**Comment by suchoss** [comment]
Proběhl datafix

```
update FirmaEvent
   set ICO = '48113328'
 where ICO = '00000000';

delete from Firma where ICO in ('0','00','000','0000','00000','000000','0000000','00000000');
```

Budeme to muset sledovat.
