### ISSUE TITLE
Propojení angažované osoby a smluv subjektu - chybný počet propojených smluv

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/HlidacStatu#91]
Profil osoby https://www.hlidacstatu.cz/osoba/anna-vancova zobrazuje v RS 2 smlouvy (celková hodnota  237 300 Kč), ale po rozkliknutí linku ZOBRAZIT PODROBNOSTI je vidět jen jedna:
![image](https://user-images.githubusercontent.com/59918383/125434284-4e0014b2-8f06-4d49-bd60-727a2ea688c3.png)
Po kliknutí na link **1 smlouva** se pak zobrazí v pořádku obě.

**Comment by michalblaha** [comment]
opraveno
