### ISSUE TITLE
Parametry pro řazení (smluv) nepokračují na dalších stránkách 

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/HlidacStatu#92]
Např. 
https://www.hlidacstatu.cz/Hledat?Q=*&order=3

na dalších stranách nefunguje to řazení "order=3" i všechny ostatní řazení (podle data, hodnoty atp.)

strana 2 - https://www.hlidacstatu.cz/Home/HledatSmlouvy?q=*&page=2

**Comment by suchoss** [comment]
Fixnuto. Bude dneska nasazeno
