### ISSUE TITLE
API smluv (dump)

### ISSUE THREAD

**Issue by lenka-crypto** [HlidacStatu/HlidacStatu#93]
viz zpráva z helpdesku z dneška

_Dobrý den,

hlásím opět potíže s API smluv, adresy typu https://www.hlidacstatu.cz/api/v1/dump?datatype=smlouvy&date=2021-07-15 vrací chybu 500. Zachytila jsem, že jste o víkendu dělali upgrade, tak tam možná vznikla nějaká chybka.

Díky za prověření,_

**Comment by michalblaha** [comment]
At pouzije API 2.0
